### PR TITLE
Update worker-links

### PR DESCRIPTION
**Pull request by SapphoSys**
This repository aims to do the following:
- Upgrade from Yarn 1 to Yarn 4. [Legacy Yarn versions are outdated.](https://twitter.com/BHolmesDev/status/1745134901223968966)
- Upgrade dependencies.
- Update the UI screenshot in README.
- Replaced legacy Wrangler 2 commands with Wrangler 3 commands. 
Note: `wrangler dev --local` is now the default behavior for `wrangler dev`.
- Use alternate Hono properties in place of deprecated ones. (example: from `c.req.headers.get` to `c.req.raw.headers.get`)

### CODE REVIEW

**Comment by Erisa** [comment]
The scope of the PR is too large.

> Upgrade from Yarn 1 to Yarn 4.

I was planning to move back to plain `npm` rather than a newer version of yarn for simplicity and because I can't remember what benefit yarn was giving me to begin with.

> Update the UI screenshot in README.

Imgur is not a reliable longterm image host (they have a history of removing old images for little reason), if not on my personal URL then it should be part of the repository.

> Replaced legacy Wrangler 2 commands with Wrangler 3 commands

I was intentionally holding it back to wrangler 2 (which is still supported for security updates) due to some issues with wrangler 3's local mode. I will need to re-evaluate and see if these are still present.

> Use alternate Hono properties in place of deprecated ones

This is fine, but I would appreciate being pointed to the documentation or changelog demonstrating these deprecations as I was not aware of them.

**Comment by SapphoSys** [comment]
> I was planning to move back to plain npm rather than a newer version of yarn for simplicity and because I can't remember what benefit yarn was giving me to begin with.

Oh! I see. Yeah that's fair. 

> Imgur is not a reliable longterm image host (they have a history of removing old images for little reason), if not on my personal URL then it should be part of the repository.

Apologies, I wasn't aware. I can upload the screenshot to the repository.

> I was intentionally holding it back to wrangler 2 (which is still supported for security updates) due to some issues with wrangler 3's local mode. I will need to re-evaluate and see if these are still present.

Fair enough!

> This is fine, but I would appreciate being pointed to the documentation or changelog demonstrating these deprecations as I was not aware of them.

This is the only changelog that I could find regarding the deprecation of some properties.
https://github.com/honojs/hono/commit/aee2093a394151208fcc4580499816ac28b2884b

**Comment by SapphoSys** [comment]
Should I make a new PR instead with your proposed changes? (and should I use npm or pnpm this time around?)

**Comment by Erisa** [comment]
I've moved away from yarn 1 and applied the new readme image in https://github.com/Erisa/worker-links/commit/41010c7d7f673697bc4fe19aefddad987e466bef (with a fix in https://github.com/Erisa/worker-links/commit/0390a8d20af5e15eaad7a22645cd572779f7792f)

Can you create a fresh PR for the hono deprecations and any dependency upgrades that are still necessary?

**Pull request closed without merging**
